# Generated by Django 5.2.6 on 2025-10-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvivarc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcObj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objName', models.CharField(max_length=100)),
                ('descr', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('curAddr', models.CharField(max_length=60)),
            ],
        ),
    ]
