# Generated by Django 5.2.6 on 2025-10-03 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lvivarc', '0002_arcobj'),
    ]

    operations = [
        migrations.AddField(
            model_name='arcobj',
            name='objType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lvivarc.arctype'),
        ),
    ]
